import type { Metadata } from "next";
import { Jaro, DotGothic16 } from "next/font/google";
import "./globals.css";

const JaroFont = Jaro({
  weight: "400",
  subsets: ["latin"],
});

const DotGothic16Font = DotGothic16({
  weight: "400",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${JaroFont.className} ${DotGothic16Font.className}`}>
        {children}
      </body>
    </html>
  );
}
