name: Release

on:
  push:
    branches:
      - "main"
jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: "read"
      id-token: "write"
    steps:
      - id: "checkout"
        uses: "actions/checkout@v4"
      - name: Authenticate to Google Cloud
        id: auth
        uses: google-github-actions/auth@v2
        with:
          token_format: access_token
          workload_identity_provider: ${{ vars.GOOGLE_IAM_WORKLOAD_IDENTITY_POOL_PROVIDER }}
          service_account: ${{ vars.GOOGLE_IAM_SERVICE_ACCOUNT }}
      - id: "upload-folder"
        uses: "google-github-actions/upload-cloud-storage@v2"
        with:
          path: ./out
          destination: ${{ vars.BUCKET }}
          parent: false
          headers: '{"Cache-Control": "public, max-age=31536000"}'
